name = "RamanujanGraphs"
uuid = "e7bd6bc6-b6b8-11e9-1ec2-2f89442c0d6c"
authors = ["Marek Kaluba <kalmar@amu.edu.pl>"]
version = "0.4.1"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"

[compat]
Graphs = "1.7"
Primes = "0.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
